# Generated by Django 5.0.7 on 2024-07-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
