# Generated by Django 5.0.7 on 2024-08-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapi', '0004_recipe_cooking_time_recipe_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='additional_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
