# Generated by Django 5.0.7 on 2024-08-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapi', '0005_recipe_additional_time_recipe_prep_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
